spring:
  application:
    name: springdrop
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration/core
management:
  endpoints:
    web:
      exposure:
        include: health,info
